# syntax=docker/dockerfile:1

FROM golang:1.22.2-alpine AS builder

# Set destination for COPY
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download


COPY . .

RUN go build -o book-purshaes ./src/app/app.go


RUN apk add --no-cache sqlite sqlite-dev


EXPOSE 2023

# Run
CMD ["./book-purshaes"]